exports.activate = function() {
    zyma.ui.notify("Hello World from Plugin!");
    // Example: append text to current editor
    // zyma.editor.insertText("\n--- Generated by HelloZyma plugin ---");
};

